CREATE TABLE istunto(
    id INT PRIMARY KEY AUTO_INCREMENT,
    tunnus VARCHAR(32) DEFAULT MD5(UUID()),
    created DATETIME DEFAULT NOW(), 
    expiry DATETIME DEFAULT DATE_ADD(NOW(), INTERVAL 1 HOUR)
);